USER = 'root'
PASSWORD = 'Blossi2003'
HOST = '127.0.0.1'
DB = 'dummydb'
AUTH = 'mysql_native_password'

'''
USER = 'root'
PASSWORD = 'mammadin'
HOST = '127.0.0.1'
DB = 'framhaldsskolaleit'
AUTH = 'Unknown'
'''